# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='is staff',
        ),
    ]
