# Generated by Django 2.0 on 2017-12-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.BooleanField(choices=[(True, 'YES prediction'), (False, 'NO prediction')], help_text='Check if YES prediction else prediction is NO', verbose_name='YES prediction')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='number of bets')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('full description', models.TextField(default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='date of publication')),
                ('estimation_end_date', models.DateTimeField(null=True, verbose_name='time when event will be probably solved')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='real event end date')),
                ('bet price', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', related_query_name='bet', to='events.Event'),
        ),
        migrations.AddField(
            model_name='bet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', related_query_name='bet', to='accounts.Player'),
        ),
    ]
