# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.BooleanField(choices=[(True, 'YES prediction'), (False, 'NO prediction')], help_text='Check if YES prediction else prediction is NO', verbose_name='YES prediction')),
                ('has', models.PositiveIntegerField(default=0, verbose_name='how many bet has')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('full description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='date of publication')),
                ('estimated_end_date', models.DateTimeField(null=True, verbose_name='time when event will be probably solved')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='real event end date')),
                ('bet price', models.IntegerField(default=50)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', related_query_name='bet', to='game.Event'),
        ),
        migrations.AddField(
            model_name='bet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', related_query_name='bet', to='account.Player'),
        ),
    ]
