# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='has',
        ),
        migrations.AddField(
            model_name='bet',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='number of bets'),
        ),
    ]
